export enum PATHS {
  GROUP_ROUTE = '/group',
  SHOPPING_LISTS = '/shopping-lists',
  EXAMPLE_SHOPPING_PAGE = '/shopping/example',
  SHOPPING_LIST_ANIME_GANG_REDUX = '/shopping-list-anime-gang-redux',
  SHOPPING_LIST_ANIME_GANG = '/shopping-list-anime-gang',
  PAIR_2_SHOPPING_PAGE = '/shopping/pair2',
  PAIR_2_SHOPPING_PAGE_REDUX = '/shopping/pair2-redux',
  PAIR3_SHOPPING_PAGE = '/shopping/pair3redux',
  PAIR_3_SHOPPING_PAGE = '/shopping/pair3',
  SHOPPING_PAGE_CHUNYU_YONGZHANG = '/shopping-lists/chunyu-yongzhang',
  JASON_YB_SHOPPING_LIST_PAGE = '/shopping-lists/jason_yb',
  JASON_YB_REDUX_SHOPPING_LIST_PAGE = '/shopping-lists/jason_yb-redux',
  SKZK_SHOPPING_PAGE = '/shopping/skzkpage',
  SKZK_SHOPPING_PAGE_REDUX = '/shopping/skzkredux',
  SHOPPING_PAGE_YIXUAN_WEIPIN = '/shopping/yixuanweipin',
  YIXUAN_WEIPIN_SHOPPING_REDUX = '/shopping/yxwp_redux',
  SHOPPING_PAGE_PAIR_FOUR = '/shopping-lists-pair-4',
  SHOPPING_PAGE_PAIR_FOUR_REDUX = '/shopping-lists-pair-4-redux',
  FRONTEND_MENTOR = '/frontendmentor',
  MARCUS_FE_MENTOR = '/frontendmentor/marcus-fe-mentor',
  FRONTEND_MENTOR_PRINCE_ENHAO = '/frontendmentor/princeenhao',
  ROCK_PAPER_SCISSORS = '/frontendmentor/rockpaperscissors',
}
